spring:
  application:
    name: account-service

server:
  port: 8081

  eureka:
    client:
      serviceUrl:
        defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 1
  leaseExpirationDurationInSeconds: 2